### ISSUE TITLE
Allow for override values on a per-method call basis

### ISSUE THREAD

**Issue by dorono** [FactomProject/factom-harmony-connect-js-sdk#40]
**UPDATE (5/16/19):** After doing some more research, we've decided NOT to put overriding properties on a separate `clientOverrides` object. Instead, we will simply be allowing developers to place those properties on the top level of the parameter object for each method. So we would be "merging-left" any of the optional property values (code example below has been updated).   

There are certain instances where we'd like to allow the user to specify override parameters that were set in the instantiation of the SDK. Right now, the parameters we're looking to allow to be overridden are:
* `appId`
* `appKey`
* `baseUrl`
* `automaticSigning`

To add optional overrides, we are going to add a new property named `clientOverrides`, which will be an object containing the aforementioned properties (`appId`, `appKey`, etc). Simply add to `clientOverrides` any properties that are part of the instantiated SDK class that you'd like to override the override.
Example:
```
await factomConnectSDK.chains.get({
    chainId: "4b9532c79d53ab22b85951b4a5853f81c2682132b3c810a95128c30401cd1e58",
    accessToken: {
        appId: "YOUR APP ID",
        appKey: "YOUR APP KEY"
    },
    baseUrl: "YOUR API URL"
});

const createChainResponse = await factomConnectSDK.chains.create({
    signerPrivateKey: keyToSign.private_key,
    signerChainId: identityChainId,
    externalIds: ["NotarySimulation", "CustomerChain", "cust123"],
    content:
        "This chain represents a notary service's customer in the NotarySimulation, a sample implementation provided as part of the Factom Harmony SDKs. Learn more here: https://docs.harmony.factom.com/docs/sdks-clients",
    automaticSigning: false
});
```

**Comment by hieumt2** [comment]
@dorono please review PR #42 updated the code and doc for this reuqest

**Comment by dorono** [comment]
@hieumt2 Hello Mai, sorry for the reversal...but we made a somewhat significant change to what we are looking for here, please see my updated description and let me know if you have any questions. Will be doing the same for the Python SDK, but will leave comments there.

**Comment by dorono** [comment]
@hieumt2 I went ahead and completed the docs and manual testing, so this one is done!
